openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8103
  description: Generated server url
paths:
  /order:
    post:
      tags:
      - order-controller
      operationId: placeOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
  /test:
    get:
      tags:
      - test-controller
      operationId: test
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
  /orders:
    get:
      tags:
      - order-controller
      operationId: getOrders
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseOrder'
  /order/inventory/{productId}:
    get:
      tags:
      - order-controller
      operationId: getOrderInventory
      parameters:
      - name: productId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/HttpErrorInfo'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
components:
  schemas:
    HttpErrorInfo:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        path:
          type: string
        message:
          type: string
        status:
          type: integer
          format: int32
        error:
          type: string
    CreateOrderRequest:
      type: object
      properties:
        customerId:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderItem:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        price:
          type: integer
          format: int64
    PurchaseOrder:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        orderStatus:
          type: string
          enum:
          - PENDING
          - COMPLETED
          - CANCELLED
    Inventory:
      type: object
      properties:
        inventoryId:
          type: integer
          format: int64
        productId:
          type: integer
          format: int64
        stock:
          type: integer
          format: int32
        history:
          type: array
          items:
            $ref: '#/components/schemas/InventoryUpdate'
    InventoryUpdate:
      type: object
      properties:
        updateId:
          type: integer
          format: int64
        inventoryId:
          type: integer
          format: int64
        orderId:
          type: integer
          format: int64
        type:
          type: string
          enum:
          - PURCHASE
          - RESTOCK
          - CUSTOMER_RETURN
          - DAMAGED
          - INVENTORY_ADJUSTMENT
          - SUPPLIER_RETURN
        quantity:
          type: integer
          format: int32
        createdAt:
          type: string
          format: date-time
