apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  # type: ClusterIP
  type: NodePort # expose the service to the outside world - for testing only
  selector:
    app: order-service-app
  ports:
  - port: 8002 #ClusterIP
    targetPort: 8080 #Pod Port
    nodePort: 30002 #ExternalIP - receive traffic from outside

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  selector:
    matchLabels:
      app: order-service-app
  replicas: 2
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
      - name: order-service
        image: ianneilagasen/e-commerce-app-order-service:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker