/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InventoryUpdate { 
    updateId?: number;
    inventoryId?: number;
    orderId?: number;
    type?: InventoryUpdate.TypeEnum;
    quantity?: number;
    createdAt?: string;
}
export namespace InventoryUpdate {
    export type TypeEnum = 'PURCHASE' | 'RESTOCK' | 'CUSTOMER_RETURN' | 'DAMAGED' | 'INVENTORY_ADJUSTMENT' | 'SUPPLIER_RETURN';
    export const TypeEnum = {
        Purchase: 'PURCHASE' as TypeEnum,
        Restock: 'RESTOCK' as TypeEnum,
        CustomerReturn: 'CUSTOMER_RETURN' as TypeEnum,
        Damaged: 'DAMAGED' as TypeEnum,
        InventoryAdjustment: 'INVENTORY_ADJUSTMENT' as TypeEnum,
        SupplierReturn: 'SUPPLIER_RETURN' as TypeEnum
    };
}


