/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItem } from './orderItem';


export interface PurchaseOrder { 
    orderId?: number;
    customerId?: number;
    items?: Array<OrderItem>;
    orderStatus?: PurchaseOrder.OrderStatusEnum;
}
export namespace PurchaseOrder {
    export type OrderStatusEnum = 'PENDING' | 'COMPLETED' | 'CANCELLED';
    export const OrderStatusEnum = {
        Pending: 'PENDING' as OrderStatusEnum,
        Completed: 'COMPLETED' as OrderStatusEnum,
        Cancelled: 'CANCELLED' as OrderStatusEnum
    };
}


